#!/bin/bash
# pull in all module products

echo make install doesn\'t do this. find out why not. meanwhile harvest...

[ -z $EPICS_BASE ] && (echo EPICS_BASE not defined; exit 1)

[ ! -z $HARVEST_VERBOSE ] && echo harvest running at $PWD

for mod in asyn recsync/client seq StreamDevice; do
	for prod in bin lib dbd; do
		[ ! -z $HARVEST_VERBOSE ] && echo cp -af ../modules/$mod/$prod/* $prod
		cp -af ../modules/$mod/$prod/* $prod
	done
done

[ ! -z HARVEST_VERBOSE ] && echo harvest complete
