#!/bin/bash
# pull in all module products

echo make install doesn\'t do this. find out why not. meanwhile harvest...

[ -z $EPICS_BASE ] && (echo EPICS_BASE not defined; exit 1)

for prod in bin lib dbd
do
        echo asyn/${prod}; cp -af ../modules/asyn/$prod/* $prod
        echo recsync/client/${prod}; cp -af ../modules/recsync/client/$prod/* $prod
        echo seq/${prod}; cp -af ../modules/seq/$prod/* $prod
        echo StreamDevice/${prod}; cp -af ../modules/StreamDevice/$prod/* $prod
done
